//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copy
    {
        public int copy_id { get; set; }
        public Nullable<bool> issue_status { get; set; }
        public Nullable<int> book_number { get; set; }
        public Nullable<int> issued_in { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
