//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int fine_number { get; set; }
        public Nullable<System.DateTime> fine_date { get; set; }
        public Nullable<int> fined_member { get; set; }
        public Nullable<int> fined_issue { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Member Member { get; set; }
    }
}
