//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<int> librarian_id { get; set; }
    
        public virtual Librarian Librarian { get; set; }
    }
}
